### PR TITLE
Fix NavBar on Mobile

### LINKED ISSUE #151: Mobile Navigation
Still need to add options to the hamburger menu when on mobile.

### PR DESCRIPTION
**Pull request by jdcaperon**
Fixes #151

### CODE REVIEW

File: static/js/navigation.js [hunk 1]
```diff
@@ -0,0 +1,25 @@
+document.addEventListener('DOMContentLoaded', () => {
+
+    // Get all "navbar-burger" elements
+    const $navbarBurgers = Array.prototype.slice.call(document.querySelectorAll('.navbar-burger'), 0);
+
+    // Check if there are any navbar burgers
+    if ($navbarBurgers.length > 0) {
+
+        // Add a click event on each of them
+        $navbarBurgers.forEach(el => {
```
Comment (nicklambourne) [inline static/js/navigation.js]: el -> element
